#!/bin/sh -xe

DOTDOTDOT_REPO=git@github.com:ingydotnet/....git

(
    cd $HOME
    if [ -d ... ]; then
        (cd ...; git pull origin master)
    else
        git clone $DOTDOTDOT_REPO
    fi
)

$HOME/.../.bin/install
